= BfR Food Process-Modeler
A JavaScript-based web editor for food processing chains
:icons: font

== Technical Requirements
This project uses npm for package management and webpack as a builder tool. For both development and production, you need to make sure that npm can be run on the machine you are using. Read more on how to install npm http://blog.npmjs.org/post/85484771375/how-to-install-npm[here].

npm will install all necessary packages and requirements for the project. Once it is available, you just need to run

[source,npm]
----
npm install
----
from the root-folder (the one that contains the "package.json" file) and the project is ready to go.

== Development
This project is mainly based on Joint.js, Backbone.js, jQuery, and Foundation Sites 6.

For the development workflow, we make heavy usage of the webpack capabilities. You can easily setup your development environment by executing the following command:

[source,npm]
----
npm run start
----

This will start the script aliased with "start". This script starts a preconfigured webpack-dev-server, initializes hot replacement for file changes, and deploys the current application on http://localhost:8080.

== Build & Deploy
If you want to build a new version from the current sources you simply need to run

[source,npm]
----
npm run build.prod
----

which starts a build script. It triggers the webpack build chain and puts the results in the "/dist" folder. The combination of that folder plus the index.html comprise the full application, ready for deploy.

[TIP]
The index.html never changes.
