= BfR Food Process-Modeler
A JavaScript-based web editor for food processing chains
:icons: font

== Technical Requirements
This project uses npm for package management and webpack as a builder tool. For both development and production, you need to make sure that npm can be run on the machine you are using. Read more on how to install npm http://blog.npmjs.org/post/85484771375/how-to-install-npm[here].

npm will install all necessary packages and requirements for the project. Once it is available, you just need to run

[source,npm]
----
npm install
----
from the root-folder (the one that contains the `package.json` file) and the project is ready to go.

== Development
This project is mainly based on Joint.js, Backbone.js, jQuery, and Foundation Sites 6.

For the development workflow, we make heavy usage of the webpack capabilities. You can easily setup your development environment by executing the following command:

[source,npm]
----
npm run start
----

This will start the script aliased with "start". This script starts a preconfigured webpack-dev-server, initializes hot replacement for file changes, and deploys the current application on http://localhost:8080.

== Build & Deploy
If you want to build a new version from the current sources you simply need to run

[source,npm]
----
npm run build.prod
----

which starts a build script. It triggers the webpack build chain and puts the results in the `dist` folder. The combination of that folder plus the `index.html` comprise the full application, ready for deploy.

[TIP]
The index.html never changes.

== Files & Folders
On your first checkout of the repository, you will find a `src` folder and several files in the root folder. Once you have run npm for the first time, an addtitional `node_modules` folder will appear. Eventually, after the first build, a `dist` folder is created. The meaning and objective of all these files and folders is as follows:

src/:: contains all source code files
dist/:: contains the production files and bundle
node_modules/:: contains all packages and libraries installed and managed via npm
package.json:: configuration file for npm which contains the name and version of all necessary packages
webpack.config.json:: configuration file for webpack which is responsible for the development workflow and the build process
config.json:: administrative configuration values that are read by the application on startup
index.html:: the main html page of the application which also loads the main JavaScript bundle
README.adoc:: AsciiDoctor source file for this documentation
README.html:: this documentation

=== Code Organization

For maintenance and extension of the application you will mostly work on the files in the `src` folder and the root folder. The source code files are organized in six subfolders:

src/cv/:: contains the "controlled vocabularies" as csv files
src/fonts/:: contains the application fonts
src/img/:: contains images and logos, that are not provided by other libraries
src/js/:: contains all JavaScript code and therefore the main logic of the application
src/scss/:: contains the stylesheet source files (Sassy CSS)
src/templates/:: contains the html templates used by the JavaScript

=== Backbone Views and Models
**WIP**

=== SCSS Organization
**WIP**
