let $ = require('jquery');
let joint = require('jointjs/dist/joint.js');
let Backbone = require('backbone');
let moment = require('moment');
let _ = require('lodash');

let timetableTemplate = require('../../templates/timetable.html');
let timetableListTemplate = require('../../templates/timetableList.html');

export let TimetableView = Backbone.View.extend({
    template: _.template(timetableTemplate),
    timetableListTemplate: _.template(timetableListTemplate),
    emptyModel: new Backbone.Model(),
    // Bind the content of the input fields to the model
    bindings: {
        '#timetableTimeInput': 'timetableTime',
        '#timetableValueInput': 'timetableValue'
    },
    // Bind events to appropriate functions
    listenerAdded: false,
    initialize: function(model, nodeId) {
        this.model = model;
        this.nodeId = nodeId;
        this.id = model.get('id');
    },
    render: function() {
        this.$el.html(this.template({model: this.model, nodeId: this.nodeId}));

        if (!this.listenerAdded) {
            this.$el.find('#timetableListSection' + this.id).html(this.timetableListTemplate({model: this.model}));
            this.addPropertyListener();
            this.addBindings();
            this.stickit();
            this.listenerAdded = true;
        }
    },

    updateLastChanged: function() {
        this.model.set('lastChanged', new Date()); // TODO
    },
    // Add a key value pair to the metadata
    addPropertyListener: function() {
        let self = this;
        this.$el.find('#addTimetableListButton').on('click', function() {
            // Add empty key value pair
            self.model.get('timeValues').push({ 0: 0});
            // Set element to the generated settings root element (generated by foundation)
            self.$el = $('.reveal-overlay');
            self.renderTimetableList();
        });

        // TODO Update last changed when edits are made
    },
    // Re-render the timetable and re-create the bindings
    renderTimetableList: function() {
        // Re-render the metadata section
        this.$el.find('#timetableListSection' + this.id).html(this.timetableListTemplate({model: this.model}));
        // Add bindings for all metadata inputs for data synchronization
        this.addBindings();
        // Scroll to bottom if the settings view is higher than the viewport
        this.$el.scrollTop(this.$el.children(':first').height());
    },
    // Add bindings for all metadata inputs for data synchronization
    addBindings: function() {
        for (let i = 0; i < this.model.get('timeValues').length; i++) { // TODO
            this.addMetadataBinding('key', i);
            this.addMetadataBinding('value', i);
            this.addRemoveButtonBinding(i);
        }
    },
    // Create a listener for the metadata attribute
    addMetadataBinding: function(type, index) {
        let self = this;
        this.$el.find('#timetableList-' + this.id + '-' + type + '-' + index).on('propertychange change click keyup input paste', function() {
            self.model.get('timeValues')[index][type] = $(this).val(); // TODO
        });
    },
    // Add a click listener remove button
    addRemoveButtonBinding: function(index) {
        let self = this;
        this.$el.find('#remove-timetable-row-' + index).on('click', function() {
            // Remove the metadata row from the array
            delete self.model.get('timeValues').splice(index, 1);
            // Re-render the section
            self.renderTimetableList();
        });
    }
});